### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by acedward** [Moblox/mongo-xlsx#5]
- [ ]  Parsing dates from an excel in returning invalida dates (internal excel model)
temporal workaround: 
``` javascript
var ms = ((numericExcelDate - (25567 - 1)) * 86400 * 1000);
var ms_offset = (new Date().getTimezoneOffset() * 60000);
var dt = new Date(ms + ms_offset);
```
- [ ]  Use underlying XLSX module directly. Will allow finer control over transformations.
- [ ]  Allow compressing arrays
e.g., 
now:   { anArray : [ 1, 'a', 3 ] , aString : 'hey' }
is converted to:

anArray[0] | anArray[1] | anArray[2]  | aString[0]
---------------|----------------|----------------|----------------
1                |  a                | 3                |  hey

it could be, optionally, converted to: 

anArray[0] | aString[0]
---------------|---------------
1, a, 3        | hey

Allowing external systems/scripts to easily access information based on column position

- [ ]  Convert to CSV
- [ ] Add Convert From XLSX tests

**Comment by acedward** [comment]
- [x] Fix performance issues. Perfomance was boosted by caching and smart iterating
- [ ]  Fix date objects (Fixed: test@ test_time.js but test are more lax)
- [x] Add Model examples and tests (more model examples needed!)
- [ ]  Add negative test so that we can check the custom-deep-comparators
- [x] Add Mongoose import/export test (Support for ObjectIDs was added)
- [x] Not using modelMap to convert from excel to json. Fixed
- [x] May not work well with mixed types for the same key. No more issues found related with  
- [x] Nested objects "first" element element may not be a numeric or string-numeric:
(ECMA-262 does not specify enumeration order. The de facto standard is to match insertion order.). But node implementation show to be stable, this will probably not changed as a new data type `SET` was added to [es2015 ](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Set) 
- [x] Very Slow :'( Some Performance Issues @ JSON.parse(JSON.stringify(x)) to make a copy and not modify original data (error1_test.json). Fixed
- [ ]  nulls, empty cells, undefined hell. Test are needed to better understand transformations

**Comment by acedward** [comment]
[ ] Update to EC6 sintax, (node v6)

**Comment by BMLande** [comment]
- i am trying to convert json to excel its done
- i need the excel records which are not added data
- for ex: 
no  A B C(header)
1.  a  b
2.  a  b  c
3.  a
in above example i need the result as row 1 and 3 are incomplete.
can you please add one method to this package which will return the excel rows which are not having data.
thanks
regards
Bhagvat Lande
